repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1 # Use the latest version
    hooks:
      - id: ruff
        args: [--fix, --exit-zero] # , --exit-non-zero-on-fix
      - id: ruff-format
